name: choRePG_${BUILD_CONTEXT}
version: '0.1'

services:

  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: choRePG_db
#    shm_size: 128mb
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
# Once the application is up and running, this port may be disabled. Good canditate to be templatized
    ports:
      - "39830:5432"

  couchdb:
    image: couchdb:latest
    restart: unless-stopped
    container_name: couchdb
    volumes:
      - couchdb-data:/opt/couchdb/data
      - couchdb-config:/opt/couchdb/etc/local.d
    environment:
      - COUCHDB_PASSWORD=${POSTGRES_PASSWORD}
      - COUCHDB_USER=${POSTGRES_USER}
    ports:
      - "5984:5984"

  web: 
    image: python:3.12
    container_name: choRePG_web
    ports: 
      - "43431:8000" 
    environment: 
      - POSTGRES_DB=${POSTGRES_DB} 
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
      - POSTGRES_HOST=db
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY} 
    volumes: 
      - ../django/django_project:/django_project
    depends_on:
      - db
    build:
      context: /${BUILD_CONTEXT}/
      dockerfile: chorepg/dockerfile
    command: python /django_project/manage.py runserver 0.0.0.0:8000
#    tty: true
    restart: unless-stopped

volumes: 
  postgres-data:
  couchdb-data:
  couchdb-config: