name: choRePG_${BUILD_CONTEXT}

services:
  db:
    image: ravendb/ravendb
    container_name: db
    ports: 
      - "41397:8080"
    volumes:
      - ravendb-data:/var/lib/ravendb/data

volumes: 
  ravendb-data: